name = "Garlic"
uuid = "154c3855-1f1e-46e8-b837-ca60023b1bfc"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]
version = "0.1.8"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cropbox = "a904b226-abf1-11e9-2713-059ba252a964"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
BSON = "0.3"
CSV = "0.8"
Cropbox = "0.3"
DataFrames = "1"
DataFramesMeta = "0.6"
Interpolations = "0.13"
TimeZones = "1"
julia = "1.6"
